######## GHTK ROAD ############################

GET https://degrassi-inukshuk-77219.herokuapp.com/Thong_tin_cuoc_hop HTTP/1.1




######## GHTK ROAD ############################

POST https://degrassi-inukshuk-77219.herokuapp.com/update_cuoc_hop HTTP/1.1
content-type: application/json

{
  "_id": "60dd8320ce04aaf4dcda9504",
  "status":0,
  "tencuochop":"asdsad",
  "nhanvien":42,
  "timebatdau": "crm",
  "noidung":435340,
  "nguoichutri":10,
  "diadiem":10,
  "ngayhop":42
}

######## GHTK ROAD ############################

DELETE  https://degrassi-inukshuk-77219.herokuapp.com/delete_cuoc_hop HTTP/1.1
content-type: application/json

{
  "_id": "60dd8320ce04aaf4dcda9504"
}

