######## GHTK ROAD ############################

GET https://degrassi-inukshuk-77219.herokuapp.com/Thong_tin_cuoc_hop HTTP/1.1




######## GHTK ROAD ############################

POST https://degrassi-inukshuk-77219.herokuapp.com/Register_cuoc_hop HTTP/1.1
content-type: application/json

{
    "status":2,
    "tencuochop": "sdcsdc",
    "nhanvien": "sdcsdc",
    "timebatdau":"sdcsdc",
    "noidung": "sdcsdc",
    "nguoichutri": "sdcsdc",
    "diadiem": "sdcsdc",
    "ngayhop": "34534534"
    
}